package modelo;

import lombok.Data;

@Data
public class EmpleadoM {

    private String CODEMP, DNIEMP, NOMEMP, APAEMP, AMAEMP, RUCEMP, EMAEMP, TELEMP, CELEMP, FECEMP, GRSEMP, ESCEMP, COLEMP,
                   CAREMP, REFEMP, LEYEMP, FEIEMP, FENEMP, DIREMP, ESTEMP, LIMEMP, REPEMP, NOAEMP, FEAEMP, AESEMP,
                   SEXEMP, PANEMP, NUHEMP, PASEMP, CUSEMP, BREEMP, RLABEMP, CATREMEMP, UNIORGEMP;
    private String CODUBI, CODREN;
}
